### ISSUE TITLE
Impossible to buy anything...

### ISSUE THREAD

**Issue by jenschr** [bitraf/p2k12#10]
After the last update, a SQL error is displayed shoeing an incorrect INSERT statement. This makes impossible to buy anything....

**Comment by jenschr** [comment]
![20170810_225421](https://user-images.githubusercontent.com/550202/29192627-5c81cdca-7e22-11e7-88ea-73c6430a8352.jpg)
Error

**Comment by jenschr** [comment]
![2017-08-10 23 20 43](https://user-images.githubusercontent.com/550202/29192689-9a35cb80-7e22-11e7-9fe1-3ed4397effd0.jpg)

**Comment by kefir-** [comment]
The picture is a little unclear, it says `VALUES ($1ld, `, right?

**Comment by mastensg** [comment]
i think this error was introduced by https://github.com/bitraf/p2k12/commit/6a68891b13309b9029720732dc247b46360b7286

`SQL_Query` has no support for `%lld`: https://github.com/bitraf/p2k12/blob/master/postgresql.c#L107

i think this was only discovered recently because the live p2k12 had been running an old version for a long time, as i was not able to build the live version at https://github.com/bitraf/p2k12/commit/b37765899c7e1fb1b44cab4437a6feb6e7a66eff

chaning the `%lld` back into `%l` will fix this, i think

**Comment by jenschr** [comment]
Cool. I can test if you update?

**Comment by mastensg** [comment]
@jenschr i am not at bitraf, so i don't have access to the p2k12 machine

you can revert 6a68891 yourself, then build but not install, and test
